package MODELO;
// Generated 22 may. 2022 18:02:12 by Hibernate Tools 5.4.32.Final

/**
 * CartasCompradas generated by hbm2java
 */
public class CartasCompradas implements java.io.Serializable {

	private String idCartaComprada;
	private String nombreCartaComprada;
	private String posicionCartaComprada;
	private String paisCartaComprada;
	private String equipoCartaComprada;
	private String ligaCartaComprada;
	private int precioCartaComprada;
	private int mediaCartaComprada;

	public CartasCompradas() {
	}

	public CartasCompradas(String idCartaComprada, String nombreCartaComprada, String posicionCartaComprada, String paisCartaComprada, String equipoCartaComprada, String ligaCartaComprada, int precioCartaComprada, int mediaCartaComprada) {
		this.idCartaComprada = idCartaComprada;
		this.nombreCartaComprada = nombreCartaComprada;
		this.posicionCartaComprada = posicionCartaComprada;
		this.paisCartaComprada = paisCartaComprada;
		this.equipoCartaComprada = equipoCartaComprada;
		this.ligaCartaComprada = ligaCartaComprada;
		this.precioCartaComprada = precioCartaComprada;
		this.mediaCartaComprada = mediaCartaComprada;
	}

	public String getIdCartaComprada() {
		return this.idCartaComprada;
	}

	public void setIdCartaComprada(String idCartaComprada) {
		this.idCartaComprada = idCartaComprada;
	}

	public String getNombreCartaComprada() {
		return this.nombreCartaComprada;
	}

	public void setNombreCartaComprada(String nombreCartaComprada) {
		this.nombreCartaComprada = nombreCartaComprada;
	}

	public String getPosicionCartaComprada() {
		return this.posicionCartaComprada;
	}

	public void setPosicionCartaComprada(String posicionCartaComprada) {
		this.posicionCartaComprada = posicionCartaComprada;
	}

	public String getPaisCartaComprada() {
		return this.paisCartaComprada;
	}

	public void setPaisCartaComprada(String paisCartaComprada) {
		this.paisCartaComprada = paisCartaComprada;
	}

	public String getEquipoCartaComprada() {
		return this.equipoCartaComprada;
	}

	public void setEquipoCartaComprada(String equipoCartaComprada) {
		this.equipoCartaComprada = equipoCartaComprada;
	}

	public String getLigaCartaComprada() {
		return this.ligaCartaComprada;
	}

	public void setLigaCartaComprada(String ligaCartaComprada) {
		this.ligaCartaComprada = ligaCartaComprada;
	}

	public int getPrecioCartaComprada() {
		return this.precioCartaComprada;
	}

	public void setPrecioCartaComprada(int precioCartaComprada) {
		this.precioCartaComprada = precioCartaComprada;
	}

	public int getMediaCartaComprada() {
		return this.mediaCartaComprada;
	}

	public void setMediaCartaComprada(int mediaCartaComprada) {
		this.mediaCartaComprada = mediaCartaComprada;
	}

}
