package MODELO;
// Generated 26 mar. 2022 13:26:16 by Hibernate Tools 5.4.32.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Carta generated by hbm2java
 */
public class Carta implements java.io.Serializable {

	private Integer idCarta;
	private String nombre;
	private String posicion;
	private String pais;
	private String equipo;
	private String liga;
	private int precio;
	private int media;
	private int ritmo;
	private int tiro;
	private int pase;
	private int regate;
	private int defensa;
	private int fisico;
	private Set <Usuario> usuarios = new HashSet(0);

	public Carta() {
	}

	public Carta(String nombre, String posicion, String pais, String equipo, String liga, int precio, int media,
			int ritmo, int tiro, int pase, int regate, int defensa, int fisico) {
		this.nombre = nombre;
		this.posicion = posicion;
		this.pais = pais;
		this.equipo = equipo;
		this.liga = liga;
		this.precio = precio;
		this.media = media;
		this.ritmo = ritmo;
		this.tiro = tiro;
		this.pase = pase;
		this.regate = regate;
		this.defensa = defensa;
		this.fisico = fisico;
	}

	public Carta(String nombre, String posicion, String pais, String equipo, String liga, int precio, int media,
			int ritmo, int tiro, int pase, int regate, int defensa, int fisico, Set usuarios) {
		this.nombre = nombre;
		this.posicion = posicion;
		this.pais = pais;
		this.equipo = equipo;
		this.liga = liga;
		this.precio = precio;
		this.media = media;
		this.ritmo = ritmo;
		this.tiro = tiro;
		this.pase = pase;
		this.regate = regate;
		this.defensa = defensa;
		this.fisico = fisico;
		this.usuarios = usuarios;
	}

	public Integer getIdCarta() {
		return this.idCarta;
	}

	public void setIdCarta(Integer idCarta) {
		this.idCarta = idCarta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getEquipo() {
		return this.equipo;
	}

	public void setEquipo(String equipo) {
		this.equipo = equipo;
	}

	public String getLiga() {
		return this.liga;
	}

	public void setLiga(String liga) {
		this.liga = liga;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public int getMedia() {
		return this.media;
	}

	public void setMedia(int media) {
		this.media = media;
	}

	public int getRitmo() {
		return this.ritmo;
	}

	public void setRitmo(int ritmo) {
		this.ritmo = ritmo;
	}

	public int getTiro() {
		return this.tiro;
	}

	public void setTiro(int tiro) {
		this.tiro = tiro;
	}

	public int getPase() {
		return this.pase;
	}

	public void setPase(int pase) {
		this.pase = pase;
	}

	public int getRegate() {
		return this.regate;
	}

	public void setRegate(int regate) {
		this.regate = regate;
	}

	public int getDefensa() {
		return this.defensa;
	}

	public void setDefensa(int defensa) {
		this.defensa = defensa;
	}

	public int getFisico() {
		return this.fisico;
	}

	public void setFisico(int fisico) {
		this.fisico = fisico;
	}

	public Set <Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set <Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
