package MODELO;
// Generated 30 mar. 2022 10:01:58 by Hibernate Tools 5.4.32.Final

/**
 * Plantilla generated by hbm2java
 */
public class Plantilla implements java.io.Serializable {

	private int idPlantilla;
	private Carta carta;
	private Usuario usuario;
	private int dinero;
	private int puntos;
	private int quimica;
	private String siglas;

	public Plantilla() {
	}

	public Plantilla(int idPlantilla, Carta carta, Usuario usuario, int dinero, int puntos, int quimica,
			String siglas) {
		this.idPlantilla = idPlantilla;
		this.carta = carta;
		this.usuario = usuario;
		this.dinero = dinero;
		this.puntos = puntos;
		this.quimica = quimica;
		this.siglas = siglas;
	}

	public int getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(int idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public Carta getCarta() {
		return this.carta;
	}

	public void setCarta(Carta carta) {
		this.carta = carta;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getDinero() {
		return this.dinero;
	}

	public void setDinero(int dinero) {
		this.dinero = dinero;
	}

	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	public int getQuimica() {
		return this.quimica;
	}

	public void setQuimica(int quimica) {
		this.quimica = quimica;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

}
