package MODELO;
// Generated 26 mar. 2022 13:26:16 by Hibernate Tools 5.4.32.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private Carta carta;
	private String nombreUsuario;
	private String contrasena;

	public Usuario() {
	}

	public Usuario(int idUsuario, Carta carta, String nombreUsuario, String contrasena) {
		this.idUsuario = idUsuario;
		this.carta = carta;
		this.nombreUsuario = nombreUsuario;
		this.contrasena = contrasena;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Carta getCarta() {
		return this.carta;
	}

	public void setCarta(Carta carta) {
		this.carta = carta;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
