package MODELO;
// Generated 30 mar. 2022 10:01:58 by Hibernate Tools 5.4.32.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nombre;
	private String usuario;
	private String contrasena;
	private String email;
	private Set plantillas = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombre, String usuario, String contrasena, String email) {
		this.nombre = nombre;
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.email = email;
	}

	public Usuario(String nombre, String usuario, String contrasena, String email, Set plantillas) {
		this.nombre = nombre;
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.email = email;
		this.plantillas = plantillas;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set <Plantilla> getPlantillas() {
		return this.plantillas;
	}

	public void setPlantillas(Set plantillas) {
		this.plantillas = plantillas;
	}

}
